site:
  title: Site Archiver
  url: https://amdphreak.github.io/site-archiver/
  start_page: site-archiver::index.adoc
content:
  sources:
    - url: ..
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ../node_modules/antora-dark-theme/supplemental-ui
output:
  dir: ./build/site
antora:
  extensions:
    - '@antora/collector-extension'
